name: kaiteki_core_backends
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.0-99.0.dev

dependencies:
  cross_file: any
  http: any
  kaiteki_core: ^0.0.1
  fediverse_objects: ^0.0.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  uuid: ^3.0.7
  oauth1:
    git: https://github.com/Kaiteki-Fedi/dart-oauth1.git
  logging: ^1.2.0
  collection: ^1.17.1
  crypto: ^3.0.3
  meta: ^1.9.1
  html: ^0.15.4

dev_dependencies:
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
  lints: ^3.0.0
  test: ^1.24.0
