name: kaiteki
repository: 'https://github.com/Craftplacer/kaiteki'
issue_tracker: 'https://github.com/Craftplacer/kaiteki/issues'
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.1.0-81.0.dev <4.0.0'

dependencies:
  anchor_scroll_controller: ^0.4.1
  animations: ^2.0.0
  async: ^2.9.0
  autoscale_tabbarview: ^1.0.2
  chewie: ^1.5.0
  collection: ^1.16.0
  copy_with_extension: ^5.0.0
  crypto: ^3.0.1
  dynamic_color: ^1.6.6
  equatable: ^2.0.5
  fast_immutable_collections: ^9.0.0
  fediverse_objects:
    git: https://github.com/Kaiteki-Fedi/fediverse_objects.git
  file_picker: ^5.0.0
  flutter:
    sdk: flutter
  flutter_blurhash:
    git: https://github.com/Craftplacer/flutter_blurhash.git
  flutter_local_notifications: ^15.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.8
  flutter_riverpod: ^2.0.2
  flutter_simple_treeview: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.0+1
  fpdart: ^1.1.0
  go_router: ^11.0.0
  google_fonts: ^6.1.0
  handy_window: ^0.3.1
  hive: ^2.2.3
  html: ^0.15.0
  http: ^1.0.0
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.0
  json_annotation: any
  kaiteki_core:
    path: ../kaiteki_core
  kaiteki_ui:
    path: ../kaiteki_ui
  logging: ^1.2.0
  markdown: ^7.0.1
  material_color_utilities: <1.0.0
  mdi: ^5.0.0-nullsafety.0
  mek_data_class: ^1.0.0
  meta: ^1.8.0
  notified_preferences: ^2.0.0
  notified_preferences_riverpod: ^1.0.0
  page_view_dot_indicator: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.0.15
  qr_bar_code_scanner_dialog: ^0.0.5
  qr_flutter: ^4.0.0
  riverpod_annotation: ^2.0.4
  share_plus: ^7.1.0
  shared_preferences: ^2.0.5
  shelf: ^1.3.0
  state_notifier: ^1.0.0
  storybook_flutter: ^0.14.0
  url_launcher: ^6.0.3
  uuid: ^3.0.6
  vector_math: ^2.1.4
  video_player: ^2.7.0

dev_dependencies:
  build_runner: ^2.1.4
  build_verify: ^3.1.0
  copy_with_extension_gen: ^5.0.0
  custom_lint: ^0.5.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.0.1
  kaiteki_lints:
    path: ../kaiteki_lints
  msix: ^3.5.1
  riverpod_generator: ^2.1.6
  test: ^1.17.10

dependency_overrides:
  sliver_tools: ^0.2.12

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icon.png
    - assets/instances.json
    - assets/languages.json
    - assets/oauth-success.html
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic-Bold.otf
          weight: 700
        - asset: assets/fonts/OpenDyslexic-Bold-Italic.otf
          weight: 700
          style: italic
    - family: Fira Mono
      fonts:
        - asset: assets/fonts/FiraMono-Regular.ttf
        - asset: assets/fonts/FiraMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/FiraMono-Bold.ttf
          weight: 700
    - family: Fira Sans
      fonts:
        - asset: assets/fonts/FiraSans-Regular.ttf
        - asset: assets/fonts/FiraSans-Italic.ttf
          style: italic
        - asset: assets/fonts/FiraSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/FiraSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/FiraSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/FiraSans-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Fira Sans Extra Condensed
      fonts:
        - asset: assets/fonts/FiraSansExtraCondensed-Regular.ttf

flutter_intl:
  enabled: true

msix_config:
  display_name: Kaiteki
  publisher_display_name: Craftplacer
  identity_name: Craftplacer.Kaiteki
  msix_version: 1.0.0.0
  # certificate_path: C:\<PathToCertificate>\<MyCertificate.pfx>
  # publisher: CN=My Company, O=My Company, L=Berlin, S=Berlin, C=DE
  logo_path: ..\..\assets\icons\windows\kaiteki.png
  start_menu_icon_path: ..\..\assets\icons\windows\kaiteki.png
  tile_icon_path: ..\..\assets\icons\windows\kaiteki.png
  # vs_generated_images_folder_path: C:\<PathToFolder>\Images
  icons_background_color: '#1e2133'
  architecture: x64
  capabilities: 'internetClient'

flutter_native_splash:
  color: "#140c0d"
  image: "assets/kaiteki-splash.png"