name: kaiteki_core
description: Kaiteki's core package.
version: 0.0.1
repository: https://github.com/Kaiteki-Fedi/kaiteki
publish_to: none

environment:
  sdk: '>=3.3.0-2.0.dev <4.0.0'

dependencies:
  equatable: ^2.0.5
  fediverse_objects:
    git: https://github.com/Kaiteki-Fedi/fediverse_objects.git
  http: ^1.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  uuid: ^3.0.7
  oauth1:
    git: https://github.com/Kaiteki-Fedi/dart-oauth1.git
  logging: ^1.2.0
  collection: ^1.17.1
  quiver: ^3.2.1
  recase: ^4.1.0
  crypto: ^3.0.3
  fast_immutable_collections: ^9.1.5
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
  lints: ^2.1.1
  test: ^1.21.0
